CREATE TABLE EMPRESA (
        ID_EMPRESA INTEGER NOT NULL,
        NOMBRE  VARCHAR(15),
        ACTIVIDAD VARCHAR(255),
        PRIMARY KEY (ID_EMPRESA)
);


CREATE TABLE AREA (
	PRIMARY KEY (ID_AREA),
        ID_AREA INTEGER NOT NULL,
	ID_EMPRESA INTEGER,
        NOMBRE  VARCHAR(15),
	constraint fk_area_id_empresa foreign key (ID_EMPRESA) REFERENCES EMPRESA       
);


CREATE TABLE CARGO (
	PRIMARY KEY (ID_CARGO),
        ID_CARGO INTEGER NOT NULL,
        NOMBRE  VARCHAR(15),
 	FUNCION VARCHAR(255),
        ID_AREA INTEGER,
	constraint fk_cargo_id_area foreign key (ID_AREA) REFERENCES AREA
        
);

CREATE TABLE EMPLEADOS (
	PRIMARY KEY (ID_EMPLEADOS),
        ID_EMPLEADOS INTEGER NOT NULL,
        NOMBRES  VARCHAR(15),
	ID_CARGO INTEGER,
  	constraint fk_EMPLEADOS_ID_CARGO foreign key (ID_CARGO) REFERENCES CARGO
        
);